<SecondWindow>:
    name: "second"

    BoxLayout:
        orientation: "vertical"
        size: root.width, root.height
        padding: 10

        Label:
            text: "Second Screen"
            font_size: 32

        Button:
            text: "Back Screen"
            font_size: 32
            on_release: 
                print('go first')
                app.root.current = "first"
                root.manager.transition.direction = "right"
